version: "3"
services:
  node: &app_base
    image: node:18.14.2-alpine
    tty: true
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    environment:
      PORT: 3000
      HOST: 0.0.0.0
    restart: always
  web-frontend:
    <<: *app_base
    ports:
      - "80:3000"
    command: yarn dev