env:
  browser: true
  es2021: true
extends:
  - 'plugin:vue/vue3-recommended'
  - '@vue/typescript/recommended'
  - 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
plugins:
  - vue
  - '@typescript-eslint'
rules: { }